### PR TITLE
refactor: check for recent alerts based on CSV file

### LINKED ISSUE #24: Fix double posting
We recently had an issue with the Metaculus Alert bot double posting stuff, see https://twitter.com/MetaculusAlert/status/1563949726097195008. 

What I did for now was just deactivate the bot altogether because I'm currently absolutely swamped with things, but that's of course not ideal. Does anyone have time to take a quick look at what might have happened and how to fix it? 
@edomt @adam-binks @Scott-Huston
Thank you very much!

### PR DESCRIPTION
**Pull request by edomt**
This PR refactors our system for checking recent alerts and avoiding double posting.

Instead of listing recent alerts by fetching recent tweets and parsing the question title (which was prone to errors), we now have a small CSV file (`alerts.csv`) that lists `question_id` and `last_alert_timestamp`.

Closes #24

### CODE REVIEW

**Comment by nikosbosse** [comment]
Thanks a ton! I'm only seeing it on my mobile, so can't check it in detail.
One important thing is that at the moment the bot is stateless, so it can't
read / write to a local csv and maintain that record.
We could have the bot be stateless and redeploy it somewhere else. Or we'd
have to write to another source, eg a Google sheet or some other storage.
Does the current version take that into account?

**Comment by edomt** [comment]
Argh, no, not at all, I forgot about the stateless aspect. Given that, I think the easiest solution would be to slightly tweak my changes to host the CSV file in S3 rather than GitHub.

**Comment by nikosbosse** [comment]
Have you used S3 buckets in the past? I've never set one up, but I can have a look at it. If it's very simple for you I'm also happy for you to take a look at it.

**Comment by edomt** [comment]
I've used them a few times, yes. But to implement I'd need my own access key for the AWS account where you've set up the bot, with read & write access to S3. If you can send this to me privately, I'm happy to try and have a look!

**Comment by nikosbosse** [comment]
The bot is currently set up on Google Cloud Functions, so I assume we would just have to create a separate account with AWS. I'm assuming Google also has something similar, but in the past I always found their stuff quite confusing...

**Comment by edomt** [comment]
Oh, sorry, I assumed this was all under AWS. No need for S3 then, we should use Google Cloud Storage :) 
So I'll need credentials for the GCP account.

**Comment by nikosbosse** [comment]
I added you to the Google Cloud Console. Did that work?

**Comment by nikosbosse** [comment]
Works like a charm as far as I can tell. Thanks a lot! There is currently one entry in the csv from 2022-08-29 (so before the current change) - did you add that there manually?

**Comment by edomt** [comment]
Yes, it was just to make sure there was at least 1 line in the CSV.

**Pull request merged**
